---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Set hostname specified in inventory file
      hostname: 
        name: "{{hostname}}"

    - name: Update hosts file
      lineinfile:   
        path: /etc/hosts 
        regexp: "^{{ hostvars[item].inventory_hostname }}.*$"
        line: "{{ hostvars[item].inventory_hostname }} {{ hostvars[item].hostname }}"
        state: present
      with_items: "{{groups['all']}}"