---
# https://github.com/PyratLabs/ansible-role-k3s/blob/main/documentation/quickstart-ha-cluster.md

- name: Build a cluster with HA control plane
  hosts: cluster
  vars:
    k3s_become_for_all: true
    k3s_etcd_datastore: true
    k3s_release_version: v1.19
  roles:
    - xanmanning.k3s