---
- hosts: primary
  gather_facts: no
  become: yes
  remote_user: ubuntu
  tasks:
    - set_fact: home_dir="{{ lookup('env','HOME') }}"

    - name: create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0775'

    - name: copy k3s.yaml
      copy:
        remote_src: yes
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/k3s.yaml
      register: k3s_config

    - name: adjust permissions on k3s.yaml
      file:
        path: /home/ubuntu/.kube/k3s.yaml
        state: file
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      when: k3s_config.changed

    - name: create kubeconfig
      copy:
        remote_src: yes
        src: /home/ubuntu/.kube/k3s.yaml
        dest: /home/ubuntu/.kube/config
      become: no
      when: k3s_config.changed

    - name: adjust permissions on kubeconfig
      file:
        path: /home/ubuntu/.kube/config
        state: file
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      become: no
      when: k3s_config.changed

    - name: update server config to point to configure inventory k3s_endpoint
      lineinfile:
        dest: /home/ubuntu/.kube/config
        regexp: '^    server: https://127.0.0.1:6443'
        line: "    server: {{ k3s_endpoint }}"
      when: k3s_config.changed

    - name: fetch kubeconfig
      ansible.builtin.fetch:
        flat: yes
        src: "/home/ubuntu/.kube/config"
        dest: "{{ home_dir }}/.kube/config"
